### ISSUE TITLE
External scripts

### ISSUE THREAD

**Issue by evanmwillhite** [drupal-pattern-lab/attach-library-twig-extension#3]
When adding an external script, the extension incorrectly prepends it with a trailing slash like `<script async="" src="/https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>`

**Comment by philwolstenholme** [comment]
Here's the example library I was using:

```yaml
global:
  css:
    theme:
      dist/style.css: {}
      dist/tailwind.css: {}
  js:
    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  dependencies:
  - core/jquery
```

Interestingly, while popper.js's path is malformed, a script tag for Bootstrap isn't loaded at all.
