### ISSUE TITLE
Only the first JS file in a library's `js` collection seems to be output to the page 

### ISSUE THREAD

**Issue by philwolstenholme** [drupal-pattern-lab/attach-library-twig-extension#5]
E.g., with this library:

```yaml
global:
  css:
    theme:
      dist/style.css: {}
      dist/tailwind.css: {}
  js:
    'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js':
      type: external
      minified: true
      attributes:
        crossorigin: anonymous
        integrity: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
```
The only output is:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>`

I think maybe because $output gets wiped out by each iteration of the forEach loop, then only passed to $stringLoader->render once.
