### ISSUE TITLE
Ability to attach dependencies of a library

### ISSUE THREAD

**Issue by philwolstenholme** [drupal-pattern-lab/attach-library-twig-extension#9]
Right now, given the code below, I believe it will only be `text-in-circle.js` that is attached:

```
text-in-circle:
  js:
    dist/03-organisms/text-in-circle/text-in-circle.js: {}
  dependencies:
  - core/jquery
  - rutherford/shave
```

It would be great (and match Drupal's behaviour) if the listed dependencies could be included too (and linked to on the page prior to `text-in-circle.js`.
